name: Build

on:
  pull_request:
    branches:
      - mainz
  push:
    branches:
      - featurez/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17.9
      - name: Install dependencies
        run: |
          npm install
      - name: Lint with eslint
        run: |
          npm run lint
